# Renders the "Sponsor" button on the GitHub repo.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [vsdudakov]
