"""Autogenerated migrations honour ``Meta.unique_together`` (P0-1).

``generate_schemas`` renders each ``unique_together`` group as an inline
``UNIQUE (...)`` clause, but the migration autogenerator used to drop it entirely
-- a freshly generated migration created the table without the constraint, so
production silently lost the uniqueness guarantee. These tests pin that the diff
now emits a ``UNIQUE`` constraint per group, that re-running makemigrations on an
unchanged model produces no new ops, and that the applied migration actually
enforces uniqueness on SQLite.
"""

import os
import tempfile

import pytest
import pytest_asyncio

from yara_orm import IntegrityError, MigrationManager, Model, YaraOrm, fields
from yara_orm.migrations import diff_states, model_state


def _op_names(ops):
    return [type(o).__name__ for o in ops]


class UtSlot(Model):
    id = fields.IntField(pk=True)
    room = fields.CharField(max_length=10)
    hour = fields.IntField()

    class Meta:
        table = "ut_slot"
        unique_together = ("room", "hour")


class UtTeam(Model):
    id = fields.IntField(pk=True)
    name = fields.CharField(max_length=20)

    class Meta:
        table = "ut_team"


class UtMember(Model):
    id = fields.IntField(pk=True)
    team = fields.ForeignKeyField("UtTeam", related_name="ut_members")
    role = fields.CharField(max_length=20)

    class Meta:
        table = "ut_member"
        unique_together = ("team", "role")


def test_unique_together_emits_unique_constraint():
    """
    GIVEN a model declaring a Meta.unique_together group
    WHEN the initial migration is diffed from an empty state
    THEN CreateModel carries a UNIQUE constraint over the group's columns
    """
    ops = diff_states({"tables": {}}, model_state([UtSlot]))
    assert _op_names(ops) == ["CreateModelIfNotExists"]
    constraints = ops[0].constraints
    assert [(c.name, c.fields) for c in constraints] == [
        ("uniq_ut_slot_room_hour", ["room", "hour"])
    ]


def test_unique_together_resolves_relation_to_fk_column():
    """
    GIVEN a unique_together group naming a forward relation
    WHEN the initial migration is diffed from an empty state
    THEN the constraint covers the relation's resolved FK db column
    """
    ops = diff_states({"tables": {}}, model_state([UtTeam, UtMember]))
    member_op = next(o for o in ops if o.table == "ut_member")
    assert [(c.name, c.fields) for c in member_op.constraints] == [
        ("uniq_ut_member_team_id_role", ["team_id", "role"])
    ]


def test_unique_together_constraint_to_source_renders_unique():
    """
    GIVEN the CreateModel op generated for a unique_together model
    WHEN it is rendered to migration source
    THEN the source reconstructs the named UniqueConstraint
    """
    ops = diff_states({"tables": {}}, model_state([UtSlot]))
    source = ops[0].to_source()
    assert "m.UniqueConstraint(fields=['room', 'hour'], name='uniq_ut_slot_room_hour')" in source


def test_unique_together_autogenerate_is_idempotent():
    """
    GIVEN an initial migration generated for a unique_together model
    WHEN its state is replayed and the model is diffed again
    THEN no further operations are produced (the constraint round-trips)
    """
    target = model_state([UtSlot])
    recorded = {"tables": {}}
    for op in diff_states({"tables": {}}, target):
        op.apply_state(recorded)
    assert diff_states(recorded, model_state([UtSlot])) == []


@pytest_asyncio.fixture
async def sqlite_orm():
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    os.remove(path)
    await YaraOrm.init(f"sqlite://{path}")
    try:
        yield
    finally:
        await YaraOrm.close()
        for suffix in ("", "-wal", "-shm"):
            if os.path.exists(path + suffix):
                os.remove(path + suffix)


@pytest.mark.asyncio
async def test_unique_together_migration_enforces_uniqueness_on_sqlite(sqlite_orm, tmp_path):
    """
    GIVEN a generated migration for a unique_together model applied on SQLite
    WHEN a duplicate group value is inserted
    THEN it raises IntegrityError while distinct values are accepted
    """
    mgr = MigrationManager(directory=str(tmp_path), app="ut_compat", models=[UtSlot])
    filename = mgr.make_migrations(name="initial")
    assert "m.UniqueConstraint" in (tmp_path / filename).read_text()
    await mgr.upgrade()

    await UtSlot.create(room="A", hour=9)
    await UtSlot.create(room="B", hour=9)  # different room
    await UtSlot.create(room="A", hour=10)  # different hour
    with pytest.raises(IntegrityError):
        await UtSlot.create(room="A", hour=9)  # duplicate (room, hour)
