//! Backend abstraction.
//!
//! Every supported database implements [`Backend`]. The Python-facing `Engine`
//! holds a `dyn Backend`, so adding MySQL or SQLite later is purely a matter of
//! providing another implementation and wiring it into [`connect`].

use async_trait::async_trait;

use crate::error::EngineError;
use crate::value::{Row, Value};

pub mod pool;
pub mod postgres;
pub mod sqlite;

#[async_trait]
pub trait Backend: Send + Sync {
    /// Run a statement that does not return rows; yields the affected row count.
    async fn execute(&self, sql: &str, params: &[Value]) -> Result<u64, EngineError>;

    /// Run a query and return every result row.
    async fn fetch_all(&self, sql: &str, params: &[Value]) -> Result<Vec<Row>, EngineError>;

    /// Like [`fetch_all`] but returns positional values (no column names),
    /// avoiding per-row name allocation and dict construction.
    async fn fetch_all_values(
        &self,
        sql: &str,
        params: &[Value],
    ) -> Result<Vec<Vec<Value>>, EngineError>;

    /// Run the same statement once per parameter set, pipelined on a single
    /// connection. Returns the first result row of each execution (empty when a
    /// statement returns nothing), preserving input order. This is the fast
    /// path for bulk inserts with `RETURNING`.
    async fn execute_many(&self, sql: &str, rows: &[Vec<Value>]) -> Result<Vec<Row>, EngineError>;

    /// Run pre-split script statements sequentially on ONE pooled connection,
    /// each in autocommit (no wrapping transaction), so session state (PRAGMA,
    /// SET, temp tables) and explicit BEGIN/COMMIT inside the script hold
    /// together, and non-transactional statements (VACUUM, CREATE INDEX
    /// CONCURRENTLY) still work. If the script leaves a transaction open, it is
    /// rolled back before the connection returns to the pool.
    async fn execute_script(&self, statements: &[String]) -> Result<(), EngineError>;

    /// Short dialect identifier (e.g. `"postgres"`); the Python layer uses this
    /// to pick a SQL dialect for query generation.
    fn dialect(&self) -> &'static str;

    /// Release pooled connections.
    async fn close(&self);

    /// Begin a transaction on a pinned connection (BEGIN already issued).
    ///
    /// `isolation`, when set, names a SQL isolation level applied at BEGIN time
    /// (e.g. `"SERIALIZABLE"`); the Python layer validates it per dialect.
    async fn begin_tx(&self, isolation: Option<&str>) -> Result<Box<dyn TxConn>, EngineError>;

    /// Whether statement futures may be driven to completion *synchronously*
    /// on the calling Python thread (the engine's opt-in sync fast path).
    ///
    /// Only meaningful for backends whose statements complete without real
    /// I/O waits (SQLite with `sync_fast_path=1` in the URL); network-backed
    /// backends must keep the default `false` — blocking a Python thread on a
    /// server round trip would stall the entire event loop for its duration.
    fn sync_capable(&self) -> bool {
        false
    }
}

/// A transaction bound to a single connection. Statements run on that
/// connection until `commit`/`rollback` consume it and return it to the pool.
///
/// Savepoints provide nesting: `savepoint`/`release`/`rollback_to` bracket a
/// sub-region so a nested block can roll back without aborting the whole
/// transaction. Names are generated by the Python layer and are safe to inline.
#[async_trait]
pub trait TxConn: Send + Sync {
    async fn execute(&self, sql: &str, params: &[Value]) -> Result<u64, EngineError>;
    async fn fetch_all(&self, sql: &str, params: &[Value]) -> Result<Vec<Row>, EngineError>;
    async fn fetch_all_values(
        &self,
        sql: &str,
        params: &[Value],
    ) -> Result<Vec<Vec<Value>>, EngineError>;
    async fn commit(self: Box<Self>) -> Result<(), EngineError>;
    async fn rollback(self: Box<Self>) -> Result<(), EngineError>;

    /// Establish a savepoint within the transaction.
    async fn savepoint(&self, name: &str) -> Result<(), EngineError>;
    /// Release (merge) a savepoint, keeping its work in the transaction.
    async fn release(&self, name: &str) -> Result<(), EngineError>;
    /// Roll back to a savepoint, discarding work done since it was set.
    async fn rollback_to(&self, name: &str) -> Result<(), EngineError>;
}

/// Whether the URL's query string carries a parameter named `key`.
///
/// Matches on the key only (everything before the first `=` of each
/// `&`-separated pair), so a value or password merely *containing* the text
/// does not trigger it.
fn url_query_has_param(url: &str, key: &str) -> bool {
    match url.split_once('?') {
        Some((_, query)) => query
            .split('&')
            .any(|pair| pair.split('=').next() == Some(key)),
        None => false,
    }
}

/// Build the appropriate backend for a connection URL.
///
/// This is the single extension point: match a new scheme here and return the
/// matching backend implementation.
pub async fn connect(url: &str) -> Result<Box<dyn Backend>, EngineError> {
    if url.starts_with("postgres://") || url.starts_with("postgresql://") {
        // `sync_fast_path` is sqlite-only: on PostgreSQL every statement is a
        // server round trip, so blocking the caller would stall the event
        // loop. Reject it explicitly rather than letting the driver's own URL
        // parser produce an obscure error (or silently ignore it).
        if url_query_has_param(url, "sync_fast_path") {
            return Err(EngineError::Config(
                "sync_fast_path is a SQLite-only URL parameter; remove it from the \
                 postgres URL"
                    .to_string(),
            ));
        }
        let backend = postgres::PgBackend::connect(url).await?;
        Ok(Box::new(backend))
    } else if url.starts_with("sqlite:") {
        let backend = sqlite::SqliteBackend::connect(url).await?;
        Ok(Box::new(backend))
    } else {
        Err(EngineError::UnsupportedUrl(url.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::url_query_has_param;

    #[test]
    fn query_param_is_matched_by_key_only() {
        assert!(url_query_has_param(
            "postgres://h/db?sync_fast_path=1",
            "sync_fast_path"
        ));
        assert!(url_query_has_param(
            "postgres://h/db?sslmode=require&sync_fast_path=0",
            "sync_fast_path"
        ));
        // A bare key (no `=value`) still counts as present.
        assert!(url_query_has_param(
            "postgres://h/db?sync_fast_path",
            "sync_fast_path"
        ));
    }

    #[test]
    fn text_outside_a_query_key_does_not_match() {
        // No query string at all.
        assert!(!url_query_has_param("postgres://h/db", "sync_fast_path"));
        // The text appearing in a *value* or in the userinfo must not match.
        assert!(!url_query_has_param(
            "postgres://h/db?application_name=sync_fast_path",
            "sync_fast_path"
        ));
        assert!(!url_query_has_param(
            "postgres://sync_fast_path:pw@h/db",
            "sync_fast_path"
        ));
    }
}
