"""Type stub for the native Rust engine module (`orm._engine`).

The real module is built by maturin from `rust/src`. Its async methods return
awaitables that resolve to Python rows; they are typed loosely here because the
values cross the PyO3 boundary dynamically.

On a SQLite engine opened with ``sync_fast_path=1`` in the URL, the statement
methods return *already-completed* awaitables (the work ran synchronously with
the GIL released); the signatures are identical — callers just ``await`` them.
``begin`` and ``execute_script`` always return pending awaitables.
"""

from collections.abc import Awaitable
from typing import Any

__version__: str

class Engine:
    @property
    def dialect(self) -> str: ...
    def execute(self, sql: str, params: list[Any] = ...) -> Awaitable[int]: ...
    def fetch_all(self, sql: str, params: list[Any] = ...) -> Awaitable[list[dict[str, Any]]]: ...
    def fetch_rows(self, sql: str, params: list[Any] = ...) -> Awaitable[list[list[Any]]]: ...
    def fetch_row(self, sql: str, params: list[Any] = ...) -> Awaitable[list[Any] | None]: ...
    def fetch_one(self, sql: str, params: list[Any] = ...) -> Awaitable[dict[str, Any] | None]: ...
    def execute_many(
        self, sql: str, rows: list[list[Any]] = ...
    ) -> Awaitable[list[dict[str, Any]]]: ...
    def execute_script(self, statements: list[str]) -> Awaitable[None]: ...
    def begin(self, isolation: str | None = ...) -> Awaitable[Transaction]: ...
    def close(self) -> Awaitable[None]: ...

class Transaction:
    def execute(self, sql: str, params: list[Any] = ...) -> Awaitable[int]: ...
    def fetch_all(self, sql: str, params: list[Any] = ...) -> Awaitable[list[dict[str, Any]]]: ...
    def fetch_rows(self, sql: str, params: list[Any] = ...) -> Awaitable[list[list[Any]]]: ...
    def fetch_row(self, sql: str, params: list[Any] = ...) -> Awaitable[list[Any] | None]: ...
    def commit(self) -> Awaitable[None]: ...
    def rollback(self) -> Awaitable[None]: ...
    def savepoint(self, name: str) -> Awaitable[None]: ...
    def release(self, name: str) -> Awaitable[None]: ...
    def rollback_to(self, name: str) -> Awaitable[None]: ...

def connect(url: str) -> Awaitable[Engine]: ...
