"""Database-side default expressions.

Pass one of these as a field's ``default`` to render a SQL ``DEFAULT`` clause in
the column DDL; the database fills the value (the column is omitted from the
``INSERT``) rather than Python computing it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .dialects import BaseDialect


class DatabaseDefault:
    """Base class for a database-side column default."""

    def to_sql(self, dialect: BaseDialect) -> str:
        """Render this default as a SQL expression for the column DDL.

        Args:
            dialect: The active SQL dialect.

        Returns:
            The SQL default expression.
        """
        raise NotImplementedError


class Now(DatabaseDefault):
    """Default to the current timestamp (``CURRENT_TIMESTAMP``)."""

    def to_sql(self, dialect: BaseDialect) -> str:
        """Render the current-timestamp default.

        Args:
            dialect: The active SQL dialect (unused; portable expression).

        Returns:
            The ``CURRENT_TIMESTAMP`` expression.
        """
        return "CURRENT_TIMESTAMP"


class RandomHex(DatabaseDefault):
    """Default to a random hex string generated by the database."""

    def __init__(self, size: int = 16) -> None:
        """Store the number of random bytes.

        Args:
            size: Number of random bytes (the hex string is twice as long).

        Returns:
            None
        """
        self.size = size

    def to_sql(self, dialect: BaseDialect) -> str:
        """Render a backend-specific random-hex expression.

        Args:
            dialect: The active SQL dialect.

        Returns:
            The random-hex default expression.
        """
        if dialect.name == "postgres":
            return "md5(random()::text || clock_timestamp()::text)"
        return f"lower(hex(randomblob({self.size})))"


class SqlDefault(DatabaseDefault):
    """Default to a verbatim SQL expression supplied by the caller."""

    def __init__(self, sql: str) -> None:
        """Store the raw SQL default expression.

        Args:
            sql: The SQL expression used as the column default.

        Returns:
            None
        """
        self.sql = sql

    def to_sql(self, dialect: BaseDialect) -> str:
        """Return the raw SQL expression.

        Args:
            dialect: The active SQL dialect (unused).

        Returns:
            The supplied SQL expression.
        """
        return self.sql


__all__ = ["DatabaseDefault", "Now", "RandomHex", "SqlDefault"]
