"""Database-side default expressions.

Pass one of these as a field's ``default`` to render a SQL ``DEFAULT`` clause in
the column DDL; the database fills the value (the column is omitted from the
``INSERT``) rather than Python computing it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .dialects import BaseDialect


class DatabaseDefault:
    """Base class for a database-side column default."""

    def to_sql(self, dialect: BaseDialect) -> str:
        """Render this default as a SQL expression for the column DDL.

        Args:
            dialect: The active SQL dialect.

        Returns:
            The SQL default expression.
        """
        raise NotImplementedError


class Now(DatabaseDefault):
    """Default to the current timestamp (``CURRENT_TIMESTAMP``)."""

    def to_sql(self, dialect: BaseDialect) -> str:
        """Render the current-timestamp default.

        Args:
            dialect: The active SQL dialect.

        Returns:
            The ``CURRENT_TIMESTAMP`` expression (``CURRENT_TIMESTAMP(6)`` on
            MySQL, whose bare spelling would truncate a ``DATETIME(6)``
            column's default to whole seconds).
        """
        if dialect.name in ("mysql", "mariadb"):
            return "CURRENT_TIMESTAMP(6)"
        return "CURRENT_TIMESTAMP"


class RandomHex(DatabaseDefault):
    """Default to a random hex string generated by the database.

    .. warning::
        The value is produced by non-cryptographic database randomness
        (PostgreSQL ``md5(random() ...)``, SQLite ``randomblob``, MySQL
        ``random_bytes``). It is fine
        for identifiers, slugs or de-duplication keys, but must **not** be used
        for security tokens (session ids, password-reset or API keys) — generate
        those in Python with :mod:`secrets` instead.
    """

    def __init__(self, size: int = 16) -> None:
        """Store the number of random bytes.

        Args:
            size: Number of random bytes (the hex string is twice as long).

        Returns:
            None
        """
        self.size = size

    def to_sql(self, dialect: BaseDialect) -> str:
        """Render a backend-specific random-hex expression.

        Args:
            dialect: The active SQL dialect.

        Returns:
            The random-hex default expression.
        """
        if dialect.name == "postgres":
            # Each md5() yields 32 lowercase hex chars (16 bytes); concatenate
            # enough of them to cover ``size`` bytes, then trim — so the width
            # honours ``size`` and matches the SQLite branch instead of always
            # being 32 chars.
            hex_len = self.size * 2
            chunks = -(-hex_len // 32)  # ceil division
            expr = " || ".join(
                f"md5(random()::text || clock_timestamp()::text || {i})" for i in range(chunks)
            )
            return f"substr({expr}, 1, {hex_len})"
        if dialect.name in ("mysql", "mariadb"):
            # ``size`` random bytes -> 2*size hex chars, same width as the
            # PostgreSQL and SQLite renderings.
            return f"lower(hex(random_bytes({self.size})))"
        if dialect.name == "oracle":
            # ``SYS_GUID()`` yields 16 random bytes -> 32 hex chars; concatenate
            # enough to cover ``size`` bytes, then trim to the same 2*size width.
            hex_len = self.size * 2
            chunks = -(-hex_len // 32)  # ceil division
            expr = " || ".join("RAWTOHEX(SYS_GUID())" for _ in range(chunks))
            return f"LOWER(SUBSTR({expr}, 1, {hex_len}))"
        return f"lower(hex(randomblob({self.size})))"


class SqlDefault(DatabaseDefault):
    """Default to a verbatim SQL expression supplied by the caller."""

    def __init__(self, sql: str) -> None:
        """Store the raw SQL default expression.

        Args:
            sql: The SQL expression used as the column default.

        Returns:
            None
        """
        self.sql = sql

    def to_sql(self, dialect: BaseDialect) -> str:
        """Return the raw SQL expression.

        Args:
            dialect: The active SQL dialect (unused).

        Returns:
            The supplied SQL expression.
        """
        return self.sql


__all__ = ["DatabaseDefault", "Now", "RandomHex", "SqlDefault"]
